modLoader="javafml"
loaderVersion="[1,)"
license="All-Rights-Reserved"

[[mods]]
modId="voxy"
version="${version}"
displayName="Voxy"
description='''Far distance rendering mod utilising LoDs. Build ${commit} at ${buildtime}'''
displayTest="IGNORE_ALL_VERSION"
logoFile="assets/voxy/icon.png"
authors="Cortex"

[[mixins]]
config="client.voxy.mixins.json"
[[mixins]]
config="common.voxy.mixins.json"
[[mixins]]
config="neoforge-common.voxy.mixins.json"

[[dependencies.voxy]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.voxy]]
modId="minecraft"
type="required"
versionRange="[${minecraft}]"
ordering="NONE"
side="BOTH"
[[dependencies.voxy]]
modId="sodium"
type="required"
versionRange="[0.8.12,0.9.0)"
ordering="NONE"
side="CLIENT"
[[dependencies.voxy]]
modId="iris"
type="optional"
versionRange="[1.8,)"
ordering="NONE"
side="CLIENT"
